import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { preloadFirebase } from "@/lib/firebase-lazy";
import { initPerformanceTracking } from "@/lib/performance";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Preload Firebase and initialize performance tracking on client side
  if (typeof window !== 'undefined') {
    preloadFirebase();
    initPerformanceTracking();
  }

  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
